# Generated by Django 4.1.1 on 2022-12-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_svs_z_rename_snippet_svs_k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svs_z',
            name='lang',
            field=models.CharField(choices=[('py', 'python'), ('js', 'java'), ('Cpp', 'С++')], max_length=30),
        ),
    ]
