# Generated by Django 4.1.1 on 2022-12-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_svs_z_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svs_k',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
