# Generated by Django 4.1.1 on 2022-12-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_svs_k_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='svs_k',
            name='rab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='svs_k',
            name='test',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='svs_k',
            name='name',
            field=models.CharField(choices=[('KVS', 'KVS')], max_length=3),
        ),
    ]
