# Generated by Django 4.1.1 on 2022-12-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_svs_k_rab_svs_k_test_alter_svs_k_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svs_k',
            name='code',
        ),
        migrations.AddField(
            model_name='svs_k',
            name='priem',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='svs_k',
            name='lang',
            field=models.CharField(max_length=300),
        ),
    ]
