# Generated by Django 4.1.1 on 2022-12-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_remove_svs_k_code_svs_k_priem_alter_svs_k_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svs_k',
            name='rab',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
