# Generated by Django 4.1.1 on 2022-12-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_svs_k_rab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='svs_k',
            old_name='creation_date',
            new_name='date',
        ),
    ]
