# Generated by Django 4.1.1 on 2022-12-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_rename_creation_date_svs_k_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svs_k',
            name='priem',
            field=models.BooleanField(default=False),
        ),
    ]
