# Generated by Django 4.1.1 on 2023-01-16 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0010_svs_z_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svs_k',
            name='name',
            field=models.CharField(choices=[('KVS-ГФИ', 'KVS-ГФИ'), ('KVS-Приемная', 'KVS-Приемная'), ('KVS-Уренгой', 'KVS-Уренгой')], max_length=12),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.svs_z')),
            ],
        ),
    ]
