# Generated by Django 4.1.1 on 2023-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_svs_z_private_alter_comment_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='svs_k',
            name='operator',
            field=models.CharField(choices=[('Ivanov I.I.', 'Иванов'), ('Petrov P.P.', 'Петров'), ('Sidorov S.S.', 'Сидоров')], default=True, max_length=13),
        ),
        migrations.AddField(
            model_name='svs_k',
            name='vedushij',
            field=models.CharField(choices=[('MinStroj', 'Минстрой'), ('MinZdrav', 'Минздрав'), ('Ektb', 'Екатеринбург')], default=True, max_length=13),
        ),
    ]
