# Generated by Django 4.1.1 on 2023-04-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_svs_k_operator_svs_k_vedushij'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svs_zz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ГУБ', 'GUB')], max_length=12)),
                ('operator', models.CharField(choices=[('Иванов', 'Ivanov'), ('Петров', 'Petrov'), ('Сидоров', 'Sidorov')], default=True, max_length=13)),
                ('vedushij', models.CharField(choices=[('Строй', 'SROY'), ('Здрав', 'ZDRAV')], default=True, max_length=13)),
                ('date', models.DateField(blank=True, null=True)),
                ('test', models.PositiveSmallIntegerField(default=0)),
                ('rab', models.PositiveSmallIntegerField(default=0)),
                ('priem', models.BooleanField(default=False)),
                ('lang', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='svs_k',
            name='vedushij',
            field=models.CharField(choices=[('ППП', 'PPP'), ('ЗППП', 'ZPPP')], default=True, max_length=13),
        ),
    ]
